### ISSUE TITLE
what is meant by my.testnet.node.tld in last step of installation instructions? 

### ISSUE THREAD

**Issue by bruceleeroy18** [mit-dci/lit#128]
Does this require a testnet node to be running on my computer, and it wants the ip address to it? 

Thanks for clarification.

**Comment by Varunram** [comment]
@bruceleeroy18 There are tow ways you can connect to testnet. One is by specifying `--tn3` to be `auto` or `1`, where lit connects to a bootstrapped testnet Seed, the other is to specify the ip of the  remote host like so `--tn3 1.2.3.4`

**Comment by Varunram** [comment]
Thanks for pointing this error out, I've fixed this in https://github.com/Varunram/lit/commit/d32285692163edcfa64ee6a214e7f37e8abaf9f6 via #127 so that its less ambiguous

**Comment by bruceleeroy18** [comment]
Thanks for the help!
