### ISSUE TITLE
Funding a channel: what are the coinType arguments? 

### ISSUE THREAD

**Issue by bruceleeroy18** [mit-dci/lit#129]
I have two nodes running, and connected on one PC. I cannot, however, get a channel open using the fund command. It seems that I am missing the coinType parameter for opening a channel.

**Comment by adiabat** [comment]
cointype is a number for different networks / chains; for testnet3 it's 1, for regtest it's 257.  The cointypes of the wallet you're currently using are displayed at the bottom in lit-af when you use the `ls` command.

**Comment by bruceleeroy18** [comment]
Thank you!


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: Tadge Dryja <notifications@github.com> Date: 12/23/17  23:55  (GMT-05:00) To: mit-dci/lit <lit@noreply.github.com> Cc: bruceleeroy18 <browningsmith@gmail.com>, Author <author@noreply.github.com> Subject: Re: [mit-dci/lit] Funding a channel: what are the coinType arguments?
  (#129) 
cointype is a number for different networks / chains; for testnet3 it's 1, for regtest it's 257.  The cointypes of the wallet you're currently using are displayed at the bottom in lit-af when you use the ls command.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mit-dci/lit","title":"mit-dci/lit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mit-dci/lit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@adiabat in #129: cointype is a number for different networks / chains; for testnet3 it's 1, for regtest it's 257.  The cointypes of the wallet you're currently using are displayed at the bottom in lit-af when you use the `ls` command."}],"action":{"name":"View Issue","url":"https://github.com/mit-dci/lit/issues/129#issuecomment-353765462"}}}
