### ISSUE TITLE
Often channel fund and push commands will fail non-recoverably

### ISSUE THREAD

**Issue by metalicjames** [mit-dci/lit#132]
This happens irrespective of the cointype or sync method. Issuing a `fund` or a `push` command hangs with the only way to recover to quit `lit-af`. Upon reopening `lit-af`, a failed `push` renders the channel unusable due to the channel being marked as busy. Upon restarting lit, if connected to the peer a `close` command will hang and a `break` command will fail with the message `nil elkrem receiver`. 

If both lit nodes are restarted the channel can be recovered, but the first push results in:
```
push error: Didn't send.  Recovered though, so try again!
```
On the counterparty side, the following log entry occurs:
```
decrypted message is 304f6e00295d2833cd9027a6a1aa44014322306559c5585aac8c1399d3cb74a95c00000000000186a0093ae18c7762332ea96a0d9fcd8a22ac62734ce150d3b44f0a28cd840162f65b7aba3beb243c7ceb76f016ad2359a5d57f4502bb3a971358b998d80094dbc91a
peerIdx is 4
routed bytes 304f6e00295d2833cd9027a6a1aa44014322306559c5585aac8c1399d3cb74a95c00000000000186a0093ae18c7762332ea96a0d9fcd8a22ac62734ce150d3b44f0a28cd840162f65b7aba3beb243c7ceb76f016ad2359a5d57f4502bb3a971358b998d80094dbc91a
message type 30
chanIdx is 4
Got DELTASIG from 4
COLLISION is (%!s(bool=true))
delta sig COLLISION (100000)
> made SH script, state 3
         revPub 03f0099b998d017d5c3c4c0a7632c8b517473789c2d781169dba812296aa797e5f timeout pub 02b89450fc31ab5b3932e33e1eceb6e23d3c83c20404cbd833a8a16ec6a5b82012
         script 632103f0099b998d017d5c3c4c0a7632c8b517473789c2d781169dba812296aa797e5f6755b2752102b89450fc31ab5b3932e33e1eceb6e23d3c83c20404cbd833a8a16ec6a5b8201268ac         scripthash 00204a39eae564369cbc834a0738de4aed581f3529eac7bce15b87b10bb58c48b395
        combined refund 038cd2b6f8941e4fe4e816618977a42256fa58395536f614bd818cfb57ef9abf86, pkh 0014a0b23c103dfa25893642de5c4fa125aaab3aaa72
____ sig verification for channel (4,4):
        input 5ca974cbd399138cac5a58c559653022430144aaa1a62790cd33285d29006e4f;0
        output 0: 0014a0b23c103dfa25893642de5c4fa125aaab3aaa72 14100000
        output 1: 00204a39eae564369cbc834a0738de4aed581f3529eac7bce15b87b10bb58c48b395 14300000
        state 3 myamt: 15100000 theiramt: 14900000
        sig: 093ae18c7762332ea96a0d9fcd8a22ac62734ce150d3b44f0a28cd840162f65b7aba3beb243c7ceb76f016ad2359a5d57f4502bb3a971358b998d80094dbc91a
PeerHandler error with 4: DeltaSigHandler err Invalid signature on chan 4 state 3
```

I will fill in the issue as I gather more information.

**Comment by Varunram** [comment]
Nice observation! I tried to reproduce this with testnet and I could. When I initially set up the funding tx, the lit node from which I tried to setup the channel hung up on me. But after restarting lit-af, the channel was there, but I couldn't push funds through.

```
	Channels:
Channel 1 (peer 2) type 1 85ad3d37518ca8687bc34da95675ee14ddf295cc8ac85d82a4369f2d96e0aa05;0
	 cap: 1000000 bal: 990000 h: -1 state: 0
```

The first problem here is (as pointed out rightly by you, the height is at -1). But I encountered something like 
```
lit-af# push 1 20000
entered command: push 1 20000
push error: peer 2 doesn't have channel 1
```
even though peer 2 has a channel. I tried to break the channel and I get a nil elkrem receiver error. I can't seem to break or close the channel now, will update this when I do.

**Comment by Varunram** [comment]
A couple more things to add
. Channels whose initialSend amounts are less that the fee seem to inevitably hang. On restarting lit-af, the channel is shown as open, but isn't actually, so trying to close or break it doesn't work (since the channel wasn't created in the first place).

Channels with a funding between 80000 to 180000 sat are one side push only, meaning only the party which setup the funding channel can send funds. If either party tries to close in such a channel, we get a message "their output amount x too low" or "my output amt -y too low". This is because the minimum  Output is configured at 100000, which means that the effective minimum channel balance is 180000 satoshi (Maybe too high?).

Close and break work well for well funded channels, though I occasionally get `nil elkrem receiver` for breaking the channel.

**Comment by metalicjames** [comment]
I think this is fixed on master now.
