### ISSUE TITLE
pubhash?

### ISSUE THREAD

**Issue by dlashua** [mit-dci/lit#140]
Trying to open a channel to my lit node from the Eclair Android App. I need a pubhash for that. "lit-af ls" shows a key like this: ln1m9yyruaprzllm8k2j450597nq4paf6vzx9qrx7

However, Eclair requires a key in this format: 021a2522abf01d932c11b2ed745319a7900ff513dbdff50272ab517eebe3554a7d

Is there a way to convert from one to the other? Or am I doing it wrong?

**Comment by Varunram** [comment]
Well, the way it works is you listen with one node and then connect to it via another. In the above example, list generates ln1m9yyruaprzllm8k2j450597nq4paf6vzx9qrx7 so you'd use that as a key to connect from your Eclair Wallet. I personally haven't used Eclair, so I can't comment on how it works, but this is the rough workflow

**Comment by dlashua** [comment]
I tried just giving it to Eclair as is. But Eclair is expecting a hexadecimal key. Not... whatever format the key in lit is in.

**Comment by dlashua** [comment]
additonally, trying to connect to a peer (using lit-af con command) fails as well, since the pubhash made available to me is in hexadecimal format, but lit is expecting... something else. 

Example, this peer works fine in clightningd, but not in lit:
03656a4c737b98b7ca5ad1ee4b411f5929f53552018b3925f341bcfa1c832287b7@104.131.26.124:9735

**Comment by Varunram** [comment]
Got it, I think the specs right now are different for lit (key is in bech32) and other lightning implementations, which is something that should be standardised pretty soon.

**Comment by dlashua** [comment]
ahhh. That makes sense. I'll see if I can find a way to convert. Without being able to do so, there's no way to connect lit to anything that I can't find the Bech32 hashed key for.

**Comment by metalicjames** [comment]
The BOLT spec and Lit are not compatible. You cannot connect c-lightning, eclair or LND with Lit.

**Comment by adiabat** [comment]
Yeah I don't even think the encrypted connections are the same, though grabbing the code / spec for the encrypted transport would be useful.

**Comment by grisha** [comment]
@metalicjames So is BOLT compatibility an eventual goal, or is Lit more of a research/educational-purpose implementation where catching up with the LN spec is less of or not at all a priority? I started looking at it as a way to learn the low-level details because I found lnd rather overwhelming, it does so many things, but soon discovered that lit does a lot of things differently.

**Comment by metalicjames** [comment]
Catching up with the BOLT spec itself is not a priority (though feature parity certainly is). BOLT is one possible LN protocol design and Lit is another. The protocol has to be different as Lit is focusing more on things like multicoin support and some newer layer-2 developments such as discreet log contracts, which BOLT at present does not support.

**Comment by alindr** [comment]
compatibiliy with other implementations is not top priority at this time for lit
