### ISSUE TITLE
Watch interface for lit-af

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#148]
The watchtower package doesn't have a lit-af interface right now. As predicted by adiabat, watchtower doesn't seem to work all that great now, so would be nice to do along with that PR (in-progress).

EDIT: PR #149

**Comment by alindr** [comment]
Is this still an issue? watchtower in general would be good to get up and running

**Comment by Varunram** [comment]
Closed via https://github.com/mit-dci/lit/issues/148
