### ISSUE TITLE
Change API provider for powless

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#156]
Not *that* big of a concern, but looks like blockexplorer.com will refer to bitcoin as "Bitcoin Legacy" (ref: https://blockexplorer.com/news/blockexplorer-support-bitcoin-cash-bitcoin-legacy/) and Bitcoin Cash as "Bitcoin" in the near future. There isn't a testnet yet for Bitcoin Cash afaik, but in the case it does come out, we should expect something similar.

**Comment by adiabat** [comment]
modified in #180
