### ISSUE TITLE
all the btc/btcd suite into lit

### ISSUE THREAD

**Issue by alindr** [mit-dci/lit#217]

**Comment by alindr** [comment]
LN Util + Btc lib - stuff that should have been in BTC util and wasn't. take the btcd wire and add the string method to tx. tx.string + tx.bytes.

**Comment by delbonis** [comment]
First step of btcd/btcsuite code in #218.

**Comment by delbonis** [comment]
Second step including moving vendored dependencies into main project in #222.

**Comment by delbonis** [comment]
Third and (hopefully) final step in #233.

**Comment by delbonis** [comment]
Completed, thanks @adiabat .
