### ISSUE TITLE
NAT Traversal

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#219]
One of the main motivations behind the need for libp2p was NAT traversal and punching. This is desirable because people behind firewalls can communicate with those who aren't, people inside a firewall can communicate with themselves, etc. Comparing the relative complexities of the implementations at hand, the best solution was to use `go-nat-pmp` and `go-UpnP` to implement NAT-PmP and NAT-UPnP  respectively. I'm opening this thread to ask for alternate suggestions that we could use without carrying too large a overhead since both the above mentioned libraries aren't active now (as was the case with libp2p-nat). PR over at #220

**Comment by gertjaap** [comment]
What about using TOR for NAT traversal? It's proven to be capable of reliably doing NAT punch through. However, I know @metalicjames mentioning that there's a unpredictable latency in communicating over TOR. Sometimes delay of up to 10 seconds happen.

Then again: The goal is an easy, reliable way of traversing NAT.

**Comment by Varunram** [comment]
TOR does way more things than plain NAT traversal, so if my intention is to just use NAT punching, I may or may not want to use tor. Not to mention the high latencies of running a node over the tor network. I think implementing our own onion routing would be more appropriate though, depends on what others think regarding this.

The PR over at #220 is fairly straightforward, but still has a couple of things we might want to add on like saving the list of ports and stuff like that.

**Comment by gertjaap** [comment]
#220 is merged so let's close this?
