### ISSUE TITLE
Split the ls command into multiple ones, clean up the main command

### ISSUE THREAD

**Issue by gertjaap** [mit-dci/lit#230]
OK, so while reviewing #224 I came to the idea of splitting up the `ls` command. 

When you issue `ls` without any parameters, it should stick to:

- Showing only open and possible pending channels
- Showing only the latest 2-3 addresses
- Show your listening address (if listening)

Then, we can add subcommands to `ls` that give more info, like

- `ls channels` would show all channels including closed ones
- `ls utxo` would show all UTXOs
- etcetera

Thoughts?

**Comment by Varunram** [comment]
Sounds good to me, I've always not liked the idea of the console getting flooded with lots of output.

**Comment by Varunram** [comment]
Maybe once we have this in place, we could look at doing something cool like a terminal UI or something as well, should be as easy as calling these commands and putting them there.

**Comment by delbonis** [comment]
Working on improving the `ls` command here: https://github.com/delbonis/lit/tree/issue320
