### ISSUE TITLE
Integrate the webui

### ISSUE THREAD

**Issue by gertjaap** [mit-dci/lit#247]
Integrate the webui into the lit repo, adjust makefile to build the GUI and integrate it as a binary resource - make lit serve the webui when it runs on a configurable port.

**Comment by Varunram** [comment]
I happened to modify this at #252 when I was looking at some stuff regarding the Makefile

**Comment by gertjaap** [comment]
Keeping this issue open for fixing the changes suggested by @adiabat in #252 

See if we can keep lit and webui separated more cleanly and have lit just serve the webui in stead of it being an electron app.

**Comment by gertjaap** [comment]
Merged #281 , so close.
