### ISSUE TITLE
Lit allows funding a channel when the coin daemon is not connected

### ISSUE THREAD

**Issue by gertjaap** [mit-dci/lit#249]
Since the funding TX cannot be published, it fails - but it never retries or recovers.

**Comment by delbonis** [comment]
Should we create some kind of "pending tx" queue that buffers the payments before they're sent to the coin daemon?  Or would it just be better to reject them altogether?

**Comment by Varunram** [comment]
I think it'd be better to reject them altogether, there's always the possibility that he doesn't realise the daemon isn't running but there are also cases where people could do annoying things, which might be better to avoid.

**Comment by delbonis** [comment]
Working on this here: https://github.com/delbonis/lit/tree/bugfix/issue249

Also some other minor fixes and stuff.

**Comment by delbonis** [comment]
Whoops nevermind.  In #255.

**Comment by Varunram** [comment]
@gertjaap Lets close this issue since the issue has been fixed.
