### ISSUE TITLE
Increase RPC Call timeout from 10s

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#254]
The current RPC Call timeout of 10s is very less and `lis` times out on a normal machine. Same goes with funding channels, we timeout but the calls are sent anyway, so this gives a false impression that the channel isn't funded and may cause problems. I think increasing the RPC Call to 30s would be a good move, happy to hear others' views.

**Comment by gertjaap** [comment]
I think RPC calls should not take that long; a call taking more than 10 seconds means we should probably split off part of it into a background thread (see #185 for instance). Do you know what causes `lis` to take that long?

It leads to pretty poor user experience if a single RPC call can take up to 30 seconds. So i think the 10 limit is already steep but okay, and forces us to optimize RPC calls to stay within that limit.

**Comment by Varunram** [comment]
Afaik, background threads do not work for listening, so I don't think that would be a solution - `lis` depends on an external `http://ipv6.myexternalip.com/raw` call that we make to announce to the tracker that could time out. This timeout occurs after 10s as well, leading to this bug.

I don't think increasing the timeout is bad for UX - 10s was arbitrary and I don't think increasing it to 20 (or even 30) would make a difference because this is an upper bound and doesn't affect users in the normal case (except if you lose your connection or something). What is bad however, is getting a timeout and trying again, only to find that the previous command was executed but lit-af didn't wait long enough. For commands like fund (which did timeout a couple times as well), you'll be opening another channel - not so nice.

**Comment by gertjaap** [comment]
That part of the code is only for announcing yourself to the tracker. You could offload that, no need to wait for that to complete. The node is already listening before that completes, so you could return from the RPC call already. My point is that RPC calls should return fast, and not block. 10 seconds is already long in my view.

**Comment by Varunram** [comment]
Agreed, but that still doesn't explain why commands like `fund` timeout which are mostly network dependent, hence the call for increasing the timeout.

**Comment by gertjaap** [comment]
Yeah, and my point is that increasing the timeout doesn't fix the actual problem. It just masks it. It shouldn't take 30 seconds for a channel to fund. And if it does, the command should return and show the channel in a Pending state in the `ls` command.

**Comment by Varunram** [comment]
Hm, my point is it *could* take 15s to `fund` because you're on a bad connection (which doesn't have to do anything with lit) and it doesn't make sense to return the RPC call while you could've waited a bit more and returned properly. As an aside, it just adds to the confusion between pending and unconfirmed.

**Comment by gertjaap** [comment]
And my point is that RPC is meant to instruct the daemon to do something. If the daemon has all the necessary info for executing the command, and it checks that input to be valid, it should execute potentially long-running commands in a background thread and not force the user / caller to wait for it to complete. 

Pending and Unconfirmed are essentially the same thing: You can't use the channel. You have to wait until it's open. Blocking the RPC call until it reaches the "Unconfirmed" state doesn't improve that.

**Comment by Varunram** [comment]
I disagree, unconfirmed is when you have the transaction broadcast to other nodes, pending is way more ambiguous - it could fail and you wouldn't know unless you listed for all the channels. Having a pending state would make you wait to see whether its pending or not, which is something the RPC must do. A RPC exists to return the success or failure of a command, running in the background simply shifts the point of catching the return, which makes *that* background call an RPC call and all the other stuff handlers, which returns you to square one where you have to wait for the RPC call to complete but just that now, you don't show it to the user, which is bad.

**Comment by Varunram** [comment]
Closing this after due discussions on this topic about behaviour being similar to how `bitcoind` handles RPC calls.
