### ISSUE TITLE
Crash while sending watch data

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#256]
When we send watch data to the same peer to which we have a connection to (which we ideally shouldn't, still), we crash with a nil pointer dereference.

**Comment by adiabat** [comment]
yeah the whole watchtower part is really old and hasn't kept up, it'll need to be modified a bunch to work with today's code.

**Comment by Varunram** [comment]
was somewhat simple in the end - fix's complexity depends on whether we want to be nice though :)

**Comment by Varunram** [comment]
Closed via https://github.com/mit-dci/lit/commit/bb8ea4beba7e1e91a70b8103d2aaad18d041401f
