### ISSUE TITLE
Breaking a channel works multiple times

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#278]
If we break a channel and no new block has been found in that interval, we can break the channel (ie execute `break` in `lit-af`)multiple times and it would still publish the same revPub and related scripts. We need to keep track of channel state breaking even before a block is mined for better UX I guess (or else, the guy may just end up breaking indefinitely till the block is mined - unnecessary panic?)

**Comment by delbonis** [comment]
Is that a bad thing?  What is there's a failure lower down and the transaction isn't published and we have to resend?

**Comment by Varunram** [comment]
Its a manual command.. If there's a failure, I shouldn't need to press `break 9` multiple times. This is similar to the RPC discussion that we had in the other issue.
