### ISSUE TITLE
Connect only to those peers associated with coin daemon(s) running

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#291]
for e.g, if I'm running regtest and testnet3 daemons, connect only to those hosts even though I may have connected to vertcoin and testnet4 peers earlier. This ensures that stuff like wrong funding, etc doesn't happen.

A direct consequence of this is that people can't passively send you money (you can't since you don't have a daemon), but that shouldn't be a problem since people generally don't expect to connect to peers whose coin daemons they don't run. If the above behaviour is needed, we could have a receive only mode where you can connect to all peers only if explicitly desired.

Leaving this open for discussion for a couple days and will put in a PR if this idea is agreed upon.

**Comment by Varunram** [comment]
PR: #293

**Comment by gertjaap** [comment]
PR is merged, closing the issue
