### ISSUE TITLE
Port the integration tests to Go

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#296]
We currently use python like bitcoin core, but it doesn't make sense to have integration tests alone in a language different from that of the parent repo. Also it makes people write stuff in two languages, which might deter some from writing proper tests. Also go is equally good in that it can accomplish what the integration tests do right now with no loss of functionality.

**Comment by gertjaap** [comment]
I don't think we're going ahead with this given that we refreshed the python suite just now.
