### ISSUE TITLE
Use the Wallit GetFee() consistently throughout lit

### ISSUE THREAD

**Issue by gertjaap** [mit-dci/lit#309]
Right now, in some places fees are not pulled from the actual wallet fee configuration. This should be used everywhere, and also be calculated properly based on the transaction size.

**Comment by Varunram** [comment]
PR: #314

**Comment by Varunram** [comment]
Closed via https://github.com/mit-dci/lit/commit/058d29915c53b1127d0935297a6191982d7a226a

**Comment by gertjaap** [comment]
PR Merged, close issue
