### ISSUE TITLE
Unable to offer a DLC to a peer, No contract found to accept

### ISSUE THREAD

**Issue by navybluesilver** [mit-dci/lit#311]
Recently it no longer works to send contracts to another peer. The contract does not seem to arrive.

For example, when running the [dlctutorial](https://github.com/mit-dci/lit-rpc-client-go-samples/blob/master/dlctutorial/dlctutorial.go):

```
Connecting nodes together...
Ensuring oracle is available...
Creating the contract...
Offering the contract to the other peer...
Waiting for the contract to be exchanged...
Accepting the contract on the other peer...
panic: No contract found to accept

goroutine 1 [running]:
main.handleError(0xa107a0, 0xc42015f6d0)
	/home/user/go/src/github.com/mit-dci/lit-rpc-client-go-samples/dlctutorial/dlctutorial.go:21 +0x86
main.main()
	/home/user/go/src/github.com/mit-dci/lit-rpc-client-go-samples/dlctutorial/dlctutorial.go:71 +0x4bb
exit status 2
```

**Comment by Varunram** [comment]
Thanks! I don't think we should panic if we don't have a contract to accept, although I don't know why the contract doesn't a drive in the first place. @gertjaap

**Comment by navybluesilver** [comment]
It is probably related to the contract having to communicate too many signatures.
