### ISSUE TITLE
Starting lit with invalid daemon name doesn't work

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#350]
Before the recent mer gets, we could still start `lit` with invalid params. Now that doesn't seem possible and we crash out. Will fix along with the other bugs reported.

**Comment by delbonis** [comment]
Isn't that a good thing?

**Comment by Varunram** [comment]
Good and bad actually. If this is good then lit must quit when it loses connection to a remote peer. If this is bad, we must fix this :) My view is that its good because we want behaviour in both cases to be identical (like it was earlier), hence the issue.

**Comment by Varunram** [comment]
Fixed in #372
