### ISSUE TITLE
Don't fatal if tracker is down

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#376]
Even if the tracker is down, stuff like `./lit-af -con pkhash@:2448` shouldn't fatal. Only if the ip is not given, it should fail. Will put in a PR to fix this.

**Comment by Varunram** [comment]
Turns out the problem is a bit bigger. Fixing.

**Comment by delbonis** [comment]
Is this fixed?

**Comment by Varunram** [comment]
I think so, yes. It was part of another commit iirc, so can't find the commit hash.
