### ISSUE TITLE
Sync doesn't work on master

### ISSUE THREAD

**Issue by Varunram** [mit-dci/lit#413]
Node sync doesn't work on master because when we receive the headers for block 4032, lit will reject it due to incorrect difficulty. This is fixed on the memberweek demo branch, so @gertjaap please do tag the relevant PR along with this issue after the demo so that we can merge it. Thanks!

**Comment by delbonis** [comment]
This was fixed iirc.

**Comment by Varunram** [comment]
Yeah, I guess we must close issues with the commit tags from next time on, can't seem to find where this was fixed.
