### ISSUE TITLE
Discrete log contracts and Noise Protocol message size limitation is 64kb.

### ISSUE THREAD

**Issue by infografx** [mit-dci/lit#449]
The issue is in that when I setup the contract as in 
the documentation:

```
dlc contract setfunding 1 100000000 100000000
dlc contract setdivision 1 20000 10000
```
the commands:

```
dlc contract ls
dlc contracts view 1
```

are not working because the max size of a go channel item is 64kb.

It just can't send all
```
 }
   "OracleValue": 19997,
   "ValueOurs": 199940000
  },
  {
   "OracleValue": 19998,
   "ValueOurs": 199960000
  }
```
values throug the channel.

====================================

The question is:

Can we change the contact so that the variables "OracleValue" and  "ValueOurs" are calculated dynamically.

Then create RPC call to retrive "ValueOurs", for example:

```
lit-af: dlc contract 1 ours 19997
```

Where 19997 is the "OracleValue".

And it will show corresponding ValueOurs:

```
lit-af: 
Command entered: dlc contract 1 ours 19997
"ValueOurs": 199940000
```

But this value have to be calculated on the client side, based on variables from

lit/dlc/contract.go:  SetContractDivision function:
```
rangeMin
rangeMax
valueAllOurs
valueAllTheirs
```
Thanks.

**Comment by infografx** [comment]
So what do you think about this.

I want to complete it but it would be great if you comment it first.

**Comment by infografx** [comment]
Ok. Maybe the answer is in whitepaper:
https://adiabat.github.io/dlc.pdf

**Comment by delbonis** [comment]
Could possibly just pass the pointer to the struct in the channel instead of the entire struct.

**Comment by infografx** [comment]
Hello guys.

I made a pointer, after that it became clear that the problem was as follows:

the file: lit/lndc/conn.go

```the function: func (c *Conn) Write(b []byte) (n int, err error)```
This function chunks large messages.

```the function: func (c *Conn) Read(b []byte) (n int, err error)```
But this function just read them. Without handling chunks.
This causes messages larger than 64 kilobytes to be processed incorrectly.

--------

Interestingly, in the LND node code, in this place is the same.

Thus, or it it has the same problem, or I do not understand something.

---------

PROPOSAL.

Wrap each message to BEGIN, and END messages.

BEGIN message format:


type RemoteControlRpcBeginMsg struct {
	PeerIdx uint32
	Idx     uint64 // Unique nonce that was sent in the request
	ChNum   bool   // Number of chunks
}

END message format (the same):

type RemoteControlRpcEndMsg struct {
	PeerIdx uint32
	Idx     uint64 // Unique nonce that was sent in the request
	ChNum   bool   // Number of chunks
}

**Comment by infografx** [comment]
The LND team tell that they are BOLT compatible.
It is interesting what behavior determines the BOLT itself.

**Comment by infografx** [comment]
The BOLT states:
Length is limited to 65535 bytes by the cryptographic wrapping, and messages in the protocol are never more than that length anyway.

This may be the reason why LND node also does not process chunks properly.
