### ISSUE TITLE
Mutex Lock Correctness

### ISSUE THREAD

**Issue by JSmith-BitFlipper** [mit-dci/lit#7]
There is a mutex lock in the function: `func (nd *LitNode) FundChannel(peerIdx uint32, ccap, initSend int64) (uint32, error)` in `.../qln/fund.go`. That lock doesn't seem to get cleared if any portion of code below it errors.

That seems bad and could easily peek up in other places throughout the code.

**Comment by JSmith-BitFlipper** [comment]
Also check out line 93 of `.../qln/netio.go`. Shouldn't the Unlock() be deferred?

**Comment by Varunram** [comment]
An old issue, but still leaving my 2 cents over here. I don't think an error should occur during plain assignment of variables (as long as the type of variables are right and they are) and therefore the lock should work as expected. @adiabat for your reference.

**Comment by adiabat** [comment]
This is probably OK / no longer relevant so closing.
