### ISSUE TITLE
NewWallit crash Error

### ISSUE THREAD

**Issue by wshbair** [mit-dci/lit#83]
Hello, 
I am trying to run the lit node using this command : llit.exe -tn3 fullnode.net -v
and I get this output 
----------------
2017/07/30 11:06:45 lit v0.1
2017/07/30 11:06:45 -h for list of options.
WARNING!! Key file not encrypted!!
Anyone who can read the key file can take everything!
You should start over and use a good passphrase!
2017/07/30 11:06:45.185152 db says 1 keys
2017/07/30 11:06:45.217740 DB height 0
2017/07/30 11:06:45.218016 DB height 1032192
2017/07/30 11:06:45.228048 opened header file .lit\testnet3\header.bin
2017/07/30 11:06:48.176676 NewWallit crash  dial tcp 122.194.229.38:18333: connectex: No connection could be made because the target machine actively refused it.
2017/07/30 11:11:56.743467 -- started BlockHandler type 1, block channel cap 8
-------------------------
Where is the problem and why the Newwalit is crashd ?

**Comment by adiabat** [comment]
"fullnode.net" is not running an actual testnet3 fullnode; replace "fullnode.net" with your bitcoin node and it will accept the connection.
