### ISSUE TITLE
How can I check micropayments are successful after closing a channel?

### ISSUE THREAD

**Issue by takaya-imai** [mit-dci/lit#9]
I connected and made a channel with other lit node and I sent 500,000satoshis.

How can I check the payments on the blockchain for testnet3? Some explorers such as blocks.io do not support segwit address yet.

The lit closed the channel after sending command "close 1" like below so I want to check the payment on blockchain explorer such as blockr.io.

```
lit-af# ls
entered command: ls

1 xxx.xxx.xxx.xxx:46664
	Channels:
Closed  1 (peer 1) f8bd9f192d34e4b3d2a4021661f7c5f7083a7270ae066d290f718159f50b32ea:0
	 cap: 1000000 bal: 500000 h: 1083882 state: 1
	Txos:
0 41cfba314ec08240c9e93cc48a1059db4331fdd59516cecaf605f6b51829a54b:0 h:1083882 amt:495000 /44'/0'/30'/1'/1'
	Addresses:
0 H5qcfNinP29CEeXWV9H54dszzPKzqEhs9nZ2c (mtiV1YhdA8As7V11SupiTunU7h14u1Ezmc)
	Utxo: 495000 Conf:495000 Channel: 500000
Sync Height 1083883
```

**Comment by narula** [comment]
Does https://testnet.blockexplorer.com/ help?

**Comment by takaya-imai** [comment]
@narula thanks.

But there are no btcs in the following (Alice sent to Bob)...

- Bob's segwit address
    - Invalid address
        - https://testnet.blockexplorer.com/address/H5qcfNinP29CEeXWV9H54dszzPKzqEhs9nZ2c
- Bob's non segwit address 
    - 0 btcs
        - https://testnet.blockexplorer.com/address/mtiV1YhdA8As7V11SupiTunU7h14u1Ezmc

This is a tx when opening the channel.  https://testnet.blockexplorer.com/tx/f8bd9f192d34e4b3d2a4021661f7c5f7083a7270ae066d290f718159f50b32ea.

**Comment by adiabat** [comment]
@takaya-imai There isn't a standard for native segwit addresses yet (I hope there can be one soon, which is probably base32)

You can still check on block explorers based on the txid.  The utxo here is 41cfba314ec08240c9e93cc48a1059db4331fdd59516cecaf605f6b51829a54b:0, so if you check a block explorer for this txid you will find it: 
https://testnet.smartbit.com.au/tx/41cfba314ec08240c9e93cc48a1059db4331fdd59516cecaf605f6b51829a54b
(smartbit has better support for segwit, but this is also visible on the explorer you linked to:
https://testnet.blockexplorer.com/tx/41cfba314ec08240c9e93cc48a1059db4331fdd59516cecaf605f6b51829a54b )

Hope this helps! よろしく

**Comment by takaya-imai** [comment]
@adiabat thanks. I could check to close a channel on smartbit.com !
