### ISSUE TITLE
Windows running lit with -tn3 throws unknown flag errors

### ISSUE THREAD

**Issue by sudheesh001** [mit-dci/lit#98]
After building the project, running `lit.ext -tn3 myfullnode.net` throws the following error

```
Error while creating a directory
unknown flag `n'
unknown flag `n'
2017/10/24 12:11:19 unknown flag `n'
```

Is this the right way to run it or am I missing something in the documentation? Digging a little into the code I realize that `-n` is not available as a possible flag, am I looking in the wrong place? https://github.com/mit-dci/lit/blob/master/lit.go#L23-L42

**Comment by Varunram** [comment]
@sudheesh001 Please run lit using `lit.ext --tn3 myfullnode.net` (two dashes with `tn3` instead of one). It was changed in a recent commit, will update the README shortly.

**Comment by adiabat** [comment]
Thanks @Varunram - docs have been updated in #99
